export const homeObjOne = {
  id: 'about',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Premium Bank',
  headLine: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged and fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjTwo = {
  id: 'discover',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Unlimited Access',
  headLine: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged and fees.',
  buttonLabel: 'Learn More',
  imgStart: false,
  img: require('../../images/svg-2.svg').default,
  alt: 'Piggybank',
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Premium Bank',
  headLine: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged and fees.',
  buttonLabel: 'Start now',
  imgStart: false,
  img: require('../../images/svg-3.svg').default,
  alt: 'Paper',
  dark: false,
  primary: false,
  darkText: true,
};